DigitalGardenSiteManager.ts, Publisher.ts, main.ts, utils.ts
* Added support for nested links and files with identical names but different location
* 🪲Bug squasing
=> Support nested links

src/Publisher.ts
Strip all between %%..%% from publishing:
https://help.obsidian.md/How+to/Format+your+notes#Comments
=> [Feat] remove obsidian comments from published files

src/Publisher.ts
**Context:** obsidian allows to transclude file headings using ![[Page#heading]] syntax. This PR tries to slice the heading when the page is transcluded using heading syntax.
**Changes**:
- Adds the partial transclusion when # is used
- Removes empty embed-title when title is not provided
=> feat: Transclude file headings

package.json, src/Publisher.ts
This PR implements 2 things:
1. Transcluded block signature to id.
2. Link in embedded section for header and block transclusion.
=> Transclusion Enhancments

src/Publisher.ts
complements https://github.com/oleeskild/digitalgarden/pull/33
=> Title passthrough

src/Publisher.ts
Complements https://github.com/oleeskild/digitalgarden/pull/34
=> Added support for dg-metatags

src/Publisher.ts
Complements https://github.com/oleeskild/digitalgarden/pull/36
Implements parts of #91
=> Tag support for all pages

main.ts, src/DigitalGardenSiteManager.ts, src/PublishModal.ts, src/PublishStatusManager.ts, src/Publisher.ts
This PR implements uploading images as assets in `src/site/img/assets` instead of hardcoding them as encoded images.
=> Dynamic image linking instead of embedding

main.ts, package.json, src/DigitalGardenSettings.ts, src/DigitalGardenSiteManager.ts, src/Publisher.ts, src/SettingView.ts
This PR implements timestamps from frontmatter.
It adds the following settings:
1. How the timestamps will be formatted.
2. Show created
3. Created key
4. Show updated
5. Updated key
Closes #150 #140
=> feat: Timestamps support

main.ts, src/DigitalGardenSettings.ts, src/DigitalGardenSiteManager.ts, src/Publisher.ts, src/SettingView.ts
I think, at least for consistency we should provide this option too.
=> Note icon on backlinks

main.ts, src/DigitalGardenSettings.ts, src/DigitalGardenSiteManager.ts, src/Publisher.ts, src/SettingView.ts
=> Hide in filetree

main.ts, src/DigitalGardenSettings.ts, src/DigitalGardenSiteManager.ts, src/PublishStatusManager.ts, src/Publisher.ts, src/SettingView.ts, src/utils.ts
Impements #157 
I've tested it on my digital garden. However, users should be warned I think.
Also, I haven't implemented `dg-path`. It will be resource-consuming to generate published note to the garden path with `dg-path`.
=> path-rewrite support

src/Publisher.ts
=> Pinned notes

src/Publisher.ts
This PR implements a feature that will allow users to hide a particular note from graphs.
=> Hide in graph

src/Publisher.ts
=> fix: 🐛 embed block reference appearence in transcluded text

.eslintrc, main.ts, package.json, src/DigitalGardenSiteManager.ts, src/PublishModal.ts, src/PublishStatusManager.ts, src/Publisher.ts, src/SettingView.ts, src/Validator.ts, src/ui/addFilterInput.ts, src/ui/suggest.ts, tsconfig.json
Hello hello hello. 
This PR fixes types and types, no logic other than two things below. 
Except for these two things:  https://github.com/oleeskild/obsidian-digital-garden/pull/394#discussion_r1324940633 and https://github.com/oleeskild/obsidian-digital-garden/pull/394#discussion_r1324941825.  . 
eslint-warnings/errors: 34 -> 0 🎂 
typescript errors: 65 -> 26 
Once we get the last ts-errors out, would suggest respecting CI-checks before PR-merges. If you don't have any big feature branches open that would cause rebase hell  it would be nice to get some semblance of directory structure in. 
🏆 yay types 🏆
=> Type balooza! 

.eslintrc, .prettierignore, .prettierrc.json, package-lock.json, package.json, src/ui/DiffView.svelte, src/ui/PublicationCenter.svelte, src/ui/TreeView/TreeNode.svelte, src/ui/TreeView/TreeView.svelte, tsconfig.json
Adds linter and prettier to svelte files for consistant editor experience. 
- fixes one any in DiffView and one prop injection for input 
NOTE: @html is dangrous but I disabled the eslint warning :)
=> Lint and format .svelte-files

main.ts, src/publisher/Publisher.ts
Publisher quits early if nothing to publish: 
Move setting validation to function and run before publish commands:
=> publishMultiple: stop if nothing to publish

src/publisher/DigitalGardenSiteManager.ts
=> Don't commit settings changes when there are no changes

main.ts, package-lock.json, package.json, scripts/generateGardenSettings.mjs, src/models/settings.ts
Sets up the simplest of loggers to allow better logging and setting log-levels
https://www.npmjs.com/package/js-logger
=> logger: add simple logger

main.ts, src/compiler/GardenPageCompiler.ts, src/publishFile/PublishFile.ts, src/publisher/DigitalGardenSiteManager.ts, src/publisher/PublishStatusManager.ts, src/publisher/Publisher.ts, src/publisher/RepositoryConnection.ts, src/test/snapshot/snapshot.md, src/ui/PublicationCenter.svelte
Changes publisher to use repository connection 
Tries to use sha when updating to be FASTER. 
Might have some bugs but tested a bunch (if bugs with caching in deletion, removed the stuff that didn't work sometimes and added cache invalidation to file tree getting)
=> Use repository connection for publishing

src/publishFile/PublishFile.ts, src/publisher/PublishStatusManager.ts, src/publisher/Publisher.ts, src/test/snapshot/generateGardenSnapshot.ts, src/test/snapshot/snapshot.md
rebased on top of (https://github.com/oleeskild/obsidian-digital-garden/pull/452), so after merging can be merged directly. 
Adds PublishFile.compare for sorting notes. 
We can add logic (dg-pinned, dg-sortweight) to this if needed! 
sorts snapshots to avoid super annoying random moving of items.
=> Add comparator to PublishFile (and sort snapshot)

src/dg-testVault/012 Callouts.md, src/dg-testVault/012-B Callouts less broken.md, src/test/snapshot/snapshot.md
Adds a couple failing test garden cases
=> test-garden: add failing callouts

src/ui/TreeView/TreeNode.svelte
=> publication center: toggle open on click

src/repositoryConnection/RepositoryConnection.ts
=> fix removing images

main.ts, src/compiler/DataviewCompiler.ts, src/test/snapshot/generateGardenSnapshot.ts, src/test/snapshot/snapshot.md
Fixes #303 
All credit goes to @bayang, who provided the solution to this in PR #303, a PR I simply forgot to ever merge into main 😬 Created a new PR, as the codebase has changed quite a bit, so it needed to be implemented in another part of the code.
=> Add support for dataview inside callout

src/dg-testVault/011 Custom updatedAt.md
=> Update 011 Custom updatedAt.md

README.md
Docs @ https://dg-docs.ole.dev/advanced/css-customization/
=> Update outdated custom CSS info in README
