- src/Publisher.ts
Heading links do not work in tables. It may be because this replacement
https://github.com/oleeskild/obsidian-digital-garden/blob/9d288f5bab36cf28b9658b16025aadc15fd6638d/src/Publisher.ts#L336
puts a pipe in the link.
So I modified these two replacements, based on the fact that `[[note#heading\|prettyName]]` works fine.
However, I haven't build the project on my end. So feel free to close this pull request if it doesn't work.
> fix: Heading Links in Table

- .gitignore
- main.ts
- src/DigitalGardenSettings.ts
- src/DigitalGardenSiteManager.ts
- src/Publisher.ts
- src/SettingView.ts
This PR adds the following items in the appearance settings:
1. Key for note icons (To set which key from frontmatter should be used for note icons, defaults to `dg-note-icon`)
2. Default note icon value (To be used for fallback)
3. Show in Filetree
4. Show in Internal Links
5. Show in Title
It transports values from 2-5 to the sites `.env` file and processes note accordingly to add maturity values.
> Note Icon support

- src/Publisher.ts
This PR implements `dataview` tables to be exported as HTML instead of markdown. This will keep dataview-specific classes intact and theming will be more seamless.
> Export dataview table with identifier class

- main.ts
- src/DigitalGardenSettings.ts
- src/Publisher.ts
- src/SettingView.ts
- src/ui/addFilterInput.ts
This feature potentially closes #77 and #302. Users can add custom filters (regex substitution) to replace parts of the note before publishing it. For example, with filter [`::: hidden(.*\n)*?:::`, ` `, `gm`], the following Markdown content will be removed before being sent to the remote repo:
```markdown
This is some normal text.
::: hidden
This is some private text that should not be published.
:::
```
For the UI, this feature adds a setting modal similar to `path rewrite rules` under the `Advanced` section:
For the backend, this feature is just adding a `.replace()` call. However, I am unfamiliar with JS development and was just borrowing code from other parts of the plugin. Please feel free to adjust it as needed. If you think this feature is appropriate and ready, we can write some …
> feat: custom filters

- src/Publisher.ts
The new custom filters feature by @zcysxy (#304) is not applied to transclutions. This small PR fixes that.
> Apply custom filters also to transclutions

- src/Publisher.ts
- src/utils.ts
Until now, `dg-permalink` was ignored while generating links to transcluded texts.
This PR fixes the issue.
> fix: 🐛 set precedence of dg-permalink in transcluded text link

- src/Publisher.ts
This should fix #358! I just split on any "string" tags on commas (plus any number of spaces) in order to generate an array of tags. 
I've tested it on my local environment and it works great. That said, I'm not certain that I've accounted for all edge cases, so please let me know if anything I've missed. Thanks!
> If tags is string, split on commas assuming CSV formatting.

- src/SettingView.ts
- Adds field in rewrite rules settings which allows user to test their rules against any path they write. 
Before attempting to fix https://github.com/oleeskild/obsidian-digital-garden/issues/289 I figured this would be a useful helper for 
1. verifying rules are working as intended 
2. documenting the rules in practice! 
I noticed while writing my own rules that to be sure the rules were working correctly I would have to set them, publish garden, go to garden and verify.
> settings: add live preview to path rewrite settings

- jest.config.js
- package.json
- src/test/utils.test.ts
relates https://github.com/oleeskild/obsidian-digital-garden/issues/289
Adds jest and a couple sanity tests, which hopefully document some utils and allow fixing functionality safely. 
Hopefully the addition of testing (and example of unit tests) will make future testing easier :) 
PS: I figured it would be better to make a tiny contained PR instead of going to fix the issue in the same one, correct me if you prefer bigger PRs!
> Add ts-jest and a couple base tests 

- main.ts
- package-lock.json
- package.json
- src/models/TreeNode.ts
- src/publisher/DigitalGardenSiteManager.ts
- src/ui/DiffView.svelte
- src/ui/PublicationCenter.svelte
- src/ui/PublishModal.ts
- src/ui/TreeView/TreeNode.svelte
- src/ui/TreeView/TreeView.svelte
- styles.css
Complete rewrite of the publication center UI. It now features a filetree where the user can select what notes to publish. It also features a diff view, letting users see what changed for "changed notes".
> Enhanced publication center UI

- .prettierignore
- src/models/settings.ts
- src/publisher/Publisher.ts
- src/test/Publisher.test.ts
- src/ui/SettingsView/GithubSettings.ts
- src/ui/SettingsView/SettingView.ts
Small feature, will hopefully make setting up easier for less tech savvy people. 
Just adds an emoji which indicates connection status. 
Also allows for validating token permissions in future (github is advocating for less powerful and more specific tokens (which is good)). Also indicates if token has expired! 
This should probably be debounced though, but these are mostly pasted so it's not that bad.
> Show github connection status

- .prettierignore
- main.ts
- src/models/frontMatter.ts
closes https://github.com/oleeskild/obsidian-digital-garden/issues/351
Adds "Toggle publication status" command. 
Adds "Remove publish flag" 
I would prefer to replace the current one, but some plugins (like button) use the name not id, so that might be breaking.
> commands: add  toggle publish flag

- main.ts
- scripts/generateGardenSettings.mjs
- src/test/snapshot/snapshot.md
- src/ui/Icon.svelte
- src/ui/PublicationCenter.svelte
- src/ui/SettingsView/SettingView.ts
- src/ui/TreeView/TreeNode.svelte
All appearence setting categories now have their own button. This should make it more obvious to users that they need to save it. 
Additionally, since the global note settings are applied right away, we now give feedback in form of a notice that the setting has been applied. 
Lastly the default timestamp key has been left blank, which is probably what most users want. Hopefully this leads to less confusion when wanting to show timestamps.
> User friendly settings

- src/ui/SettingsView/GithubSettings.ts
Nothing to see here, just debounces cred check so it doesn't ping github on every keystroke
> githubsettings: debounce cred-check

- main.ts
- src/compiler/FrontmatterCompiler.ts
- src/compiler/GardenPageCompiler.ts
- src/publisher/PublishFile.ts
- src/publisher/PublishStatusManager.ts
- src/publisher/Publisher.ts
- src/publisher/Validator.ts
- src/test/snapshot/generateGardenSnapshot.ts
- src/ui/PublicationCenter.svelte
Abstracts file to class, it can compile itself and return things. 
Ideally it would handle it's own metadata too, and the compiler could be less complex. 
Then we can do 
`type TCompiler = (PublishFile) => string`
and inside a compiler: 
```ts
const icon = publishFile.meta.getIcon 
```
instead of stuff like this: 
```ts
const noteIconKey = this.settings.noteIconKey;
if (baseFrontMatter[noteIconKey] !== undefined) {
publishedFrontMatter["noteIcon"] = baseFrontMatter[noteIconKey];
} else {
publishedFrontMatter["noteIcon"] = this.settings.defaultNoteIcon;
}
```
It COULD be that we'd want PublishFile to extend TFile. Also not 100% on the name PublishFile.
> Abstract file into class

- src/publisher/DigitalGardenSiteManager.ts
- src/publisher/RepositoryConnection.ts
- src/publisher/TemplateManager.ts
- src/test/snapshot/generateGardenSnapshot.ts
- src/test/snapshot/snapshot.md
- src/ui/DigitalGardenSettingTab.ts
- src/ui/SettingsView/SettingView.ts
Speeds up updating by: 
- getting sitemap of template 
- getting sitemap of user template 
- checking files to change / add against sha's in sitemaps 
Updating only updates files that were marked to update. 
Settings UI needs some love, but added a quick change that it disables the update modal if template is up to date.
> Speed up PR updating / update checking 

- main.ts
It seems main.ts had dotenv imported, which is probably what's breaking on mobile. Removes, as it isn't needed.
> fix: fix garden on mobile

- src/compiler/GardenPageCompiler.ts
Obsidian replaces some special characters (e.g. `:`) from the header if selected from the autocomplete. This leads to a header mismatch on transclusion.
This PR compares headers by converting them to slugs to mitigate this issue.
> fix: 🐛 header transclusion

- src/compiler/GardenPageCompiler.ts
- src/compiler/createBlockIDs.test.ts
- src/compiler/replaceBlockIDs.ts
- src/dg-testVault/015 Code blocks.md
- src/test/snapshot/snapshot.md
Fixes #595 (which i reported)
The title of this PR is a little too narrow compared to what this PR actually does (~~preserves code blocks~~ actually not quite, see #599), but I wanted to match [the issue](https://github.com/oleeskild/obsidian-digital-garden/issues/595) that I'd opened.
Took a quick stab at *not* replacing `^block-ids` within markdown codeblocks.
Overview of the changes:
- Added a new note: `src/dg-testVault/015 Code blocks.md`
- Pulled the replacement operation out of `createBlockIDs` into its own file/function (`replaceBlockIDs`) so it could be tested independently of the compiler
- Added a test for the new `replaceBlockIDs` fn
The actual mechanism for preserving block IDs within codeblocks is pretty simplistic:
1. Extract and replace code blocks with placeholders: the …
> fix: don't replace block IDs in codeblocks

- README.md
Quick comment on where to find the main entry point. 
I needed to extend the template a bit and had to poke around a bit before i figured out how this is pieced together. This comment might spare the next person.
> (docs): document templating entry point

- src/compiler/replaceBlockIDs.ts
- src/publishFile/ObsidianFrontMatterEngine.ts
- src/utils/regexes.ts
Some of the used regex definitions only looked for `\n` (LF) and not for `\r\n` (CRLF). Because I'm using Windows and sometimes modify files with other editors it can happen that files are saved with CRLF line endings .
This PR changes the regexes that they find both, LF and CRLF.
Fixes #615
> Find CRLF line endings (Windows) with regexes

- src/compiler/FrontmatterCompiler.ts
On notes that are marked as home a tag `gardenEntry` gets added. Because the method can get executed multiple times, it could happen, that the tag was added multiple times.
> Fix duplicated tag 'gardenEntry'

- src/compiler/GardenPageCompiler.ts
- src/dg-testVault/P Plugins/PD Dataview/PD5.1 Dataview in transclusions.md
- src/dg-testVault/P Plugins/PD Dataview/PD5.2 Dataview in transclusions.md
- src/test/snapshot/snapshot.md
> :bug: replace dataview queries in transcluded text content

- src/compiler/GardenPageCompiler.ts
When "`![[]]`或者`[[]]`" exists in markdown, the document is rendered repeatedly, because if the path passed to the getFirstLinkpathDest function is an empty string, the current document is returned.
> fix document rendered repeatedly bug

- src/views/SettingsView/GithubSettings.ts
The README recommends fine-grained tokens since #489, so the settings view should match
> fix: link to fine-grained token docs in settings view
